resource_group_name = "Terraform-Test-databricks"
storage_account_name = "test"
location = "canada central"
Databrick_workspace_name = "TestDatabrick001"
subnet_id = ""
vnet_id = ""
vnet_resourcegroup_name = ""
vnet_name = ""
